### ISSUE TITLE
Center position of guide text box

### ISSUE THREAD

**Issue by thomas-maschler** [crowdcover/logging-roads#20]
Position of text box in guide section should be the same as on first slide/ leaderboard.
Try to not stretch background photo

**Comment by jameslaneconkling** [comment]
done.

some stretching of background photos is inevitable, as I've set a limit on all bg photo widths of 1200px.  Anything larger will increase load times.  Already, I'm thinking that in order to decrease load times we should remove bg photos altogether, though I never found a bg color scheme that was as compelling.

I think this is good enough for now.
